

//权限类型
#define ATP_ADMINISTRATOR	1
#define ATP_MANAGER			2
#define ATP_USER			3


//
#define OPERATELOG  1
#define ALGOLOG		2



//权限
#define PERMISSION 0

#define ADMIN_ADDMANAGER		(PERMISSION+1)
#define ADMIN_VIEWMANAGER		(PERMISSION+2)
#define ADMIN_MODIFYMANAGER		(PERMISSION+3)
#define ADMIN_DISABLEMANAGER	(PERMISSION+4)
#define ADMIN_DELMANAGER		(PERMISSION+5)

#define ADMIN_ADDSERVER			(PERMISSION+6)
#define ADMIN_VIEWSERVER		(PERMISSION+7)
#define ADMIN_MODIFYSERVER		(PERMISSION+8)
#define ADMIN_DISABLESERVER		(PERMISSION+9)
#define ADMIN_DELSERVER			(PERMISSION+10)

#define ADMIN_VIEWLOG			(PERMISSION+11)

//////////////////////////////////////////////////////////////////////////

#define MANAGER_ADDALGO			(PERMISSION+12)
#define MANAGER_RELALGO			(PERMISSION+13)
#define MANAGER_MODIFYALGO		(PERMISSION+14)
#define MANAGER_VIEWALGO		(PERMISSION+15)
#define MANAGER_DISABLEALGO		(PERMISSION+16)
#define MANAGER_DELALGO			(PERMISSION+17)

#define MANAGER_ADDUSER			(PERMISSION+18)
#define MANAGER_VIEWUSER		(PERMISSION+19)
#define MANAGER_MODIFYUSER		(PERMISSION+20)
#define MANAGER_DISABLEUSER		(PERMISSION+21)
#define MANAGER_DELUSER			(PERMISSION+22)

#define MANAGER_VIEWMANAGER		(PERMISSION+23)
#define MANAGER_MODIFYMANAGER	(PERMISSION+24)

#define MANAGER_VIEWLOG			(PERMISSION+25)

//////////////////////////////////////////////////////////////////////////

#define USER_ADDALGO			(PERMISSION+26)
#define USER_RUN_STOP_ALGO		(PERMISSION+27)
#define USER_MODIFYALGO			(PERMISSION+28)
#define USER_VIEWALGO			(PERMISSION+29)
#define USER_DELALGO			(PERMISSION+30)

#define USER_VIEWUSER			(PERMISSION+31)
#define USER_MODIFYUSER			(PERMISSION+32)

#define USER_VIEWLOG			(PERMISSION+33)



//错误值